mam_cc_CC=/Users/kfisher/pads/ast-ast/arch/darwin.i386/bin/cc
mam_cc_NATIVE=/Users/kfisher/pads/ast-ast/arch/darwin.i386/bin/cc
mam_cc_EXECTYPE=darwin.i386
mam_cc_HOSTTYPE=darwin.i386
mam_cc_ALTPP_FLAGS=
mam_cc_ALTPP_ENV=
mam_cc_AR=/usr/bin/ar
mam_cc_ARFLAGS=
mam_cc_DEBUG=-g
mam_cc_DIALECT=ANSI DOTI GNU DYNAMIC -dD -L
mam_cc_DLLBIG=-D_BLD_DLL -fPIC
mam_cc_DLLSMALL=-D_BLD_DLL -fpic
mam_cc_DLL=-D_BLD_DLL -fPIC
mam_cc_DLL_DEF=-D_BLD_DLL
mam_cc_DLL_DIR=${LIBDIR}
mam_cc_DLL_LIBRARIES=-lm -lc
mam_cc_DLL_VARIANTS=
mam_cc_DYNAMIC=
mam_cc_EXPORT_DYNAMIC=
mam_cc_INCLUDE_LOCAL=
mam_cc_LD=/usr/bin/ld
mam_cc_LD=/Users/kfisher/pads/ast-ast/arch/darwin.i386/bin/cc
mam_cc_LD_DYNAMIC=
mam_cc_LD_LAZY=
mam_cc_LD_NOLAZY=
mam_cc_LD_ORIGIN=
mam_cc_LD_RECORD=
mam_cc_LD_NORECORD=
mam_cc_LD_RUNPATH=-Wl,-rpath,
mam_cc_LD_STATIC=
mam_cc_LD_STRIP=
mam_cc_LIB_DLL=symbol
mam_cc_LIB_ALL=-all_load
mam_cc_LIB_UNDEF=
mam_cc_MAKE_OPTIONS=
mam_cc_NM=/usr/bin/nm
mam_cc_NMEDIT=-e '/[ 	]T[ 	][ 	]*[_ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz]/!d' -e 's/.*[ 	]T[ 	][ 	]*//'
mam_cc_NMFLAGS=
mam_cc_OPTIMIZE=-O
mam_cc_PICBIG=-fPIC
mam_cc_PICSMALL=-fpic
mam_cc_PIC=-fPIC
mam_cc_READONLY=
mam_cc_REPOSITORY=
mam_cc_RUNPATH=
mam_cc_SHARED=-G
mam_cc_SHARED_LD=/Users/kfisher/pads/ast-ast/arch/darwin.i386/bin/cc
mam_cc_SHARED_REGISTRY=
mam_cc_SHARED_REGISTRY_PATH=${LIBDIR}/registry.ld
mam_cc_SHELLMAGIC=
mam_cc_SIZE=/usr/bin/size
mam_cc_STATIC=
mam_cc_STDINCLUDE=/usr/local/include /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.0/include /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include /usr/include /System/Library/Frameworks /Library/Frameworks /usr/include/libkern/i386
mam_cc_STDLIB=/usr/local/lib /usr/lib
mam_cc_STRICT=-ansi -pedantic
mam_cc_STRIP=/usr/bin/strip
mam_cc_STRIP_FLAGS=
mam_cc_PREFIX_ARCHIVE=lib
mam_cc_PREFIX_DYNAMIC=
mam_cc_PREFIX_SHARED=lib
mam_cc_PREFIX_SYMBOL=_
mam_cc_SUFFIX_ARCHIVE=.a
mam_cc_SUFFIX_COMMAND=
mam_cc_SUFFIX_DYNAMIC=
mam_cc_SUFFIX_LD=.ld
mam_cc_SUFFIX_OBJECT=.o
mam_cc_SUFFIX_SHARED=.so
mam_cc_SUFFIX_SOURCE=.c
mam_cc_SUFFIX_STATIC=
mam_cc_VERSION=--version
mam_cc_VERSION_STRING=Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
mam_cc_WARN=-Wall
mam_cc_L=1
_hosttype_=${mam_cc_HOSTTYPE}
STDCAT=/bin/cat
STDCHMOD=/bin/chmod
STDCMP=/usr/bin/cmp
STDCP=/bin/cp
STDED=ed
STDEDFLAGS=-
STDLN=/bin/ln
STDMV=/bin/mv
STDRM=/bin/rm
PADS_CC_IS_GNU=1
