
.SUFFIXES:

%: forceabort
	@echo " "
	@echo " "
	@echo "There are no make targets in this directory."
	@echo "You probably meant to do gmake in the tests subdir?"
	@echo " "
	@echo " "
	@exit 1

forceabort: ;

