//
// These macros are called by the C code that is generated by gigascope_make.pl
//

#ifndef PDCI_MacroArg2String
#define PDCI_MacroArg2String(s) #s
#endif

#define HDR_GET_FN(ty, field) \
int get_pads_ ## field (struct packet *p, ty *r) { \
  if (global_hdr_pd.field.nerr) return -1; \
  *r = (ty)global_hdr.field; \
  return 0; \
}

#define REC_GET_FN(ty, field) \
int get_pads_ ## field (struct packet *p, ty *r) { \
  if (global_rec_pd.field.nerr) return -1; \
  *r = (ty)global_rec.field; \
  return 0; \
}

#define HDR_GET_STR_FN(ty, field) \
int get_pads_ ## field (struct packet *p, struct string *r) { \
  if (global_hdr_pd.field.nerr) return -1; \
  r->data = global_hdr.field.str; \
  r->length = global_hdr.field.len; \
  r->owner = 0; \
  return 0; \
}

#define REC_GET_STR_FN(ty, field) \
int get_pads_ ## field (struct packet *p, struct string *r) { \
  if (global_rec_pd.field.nerr) return -1; \
  r->data = global_rec.field.str; \
  r->length = global_rec.field.len; \
  r->owner = 0; \
  return 0; \
}

